### ISSUE TITLE
0 downloads user should be vanished

### ISSUE THREAD

**Issue by mataki** [mataki/rubygems-leader#10]

**Comment by randym** [comment]
You should be able to do something like this now:

```
heroku run rake rubygems-leader:cleanup RAILS_ENV=production
```

This will remove all existing users that have  0 total downloads. 

_The RAILS_ENV bit may be redundant. I would not be surprised if this was already set in heroku's environment._

The fetcher will also now skip any new updates/inserts for the same.

**Comment by mataki** [comment]
That task is failed on heroku.

```
ActiveRecord::Base.establish_connection(config[RAILS_ENV])
```

Perhaps config/database.yml is not used on heroku.

**Comment by randym** [comment]
Just thinking logically

```
task foo: :environment do
```

should be loading up everything anyway so it is probably better to just do:

```
Users.where(total_downloads: 0).delete_all
```

and skip all that connection garbage. I expect it will run the same sql anyway.

Ill have a hack at this later on today and send in a PR

**Comment by randym** [comment]
pull request to fix this is up.
https://github.com/mataki/rubygems-leader/pull/13
