### ISSUE TITLE
Data not updated on http://rubygems-leader.herokuapp.com

### ISSUE THREAD

**Issue by imanel** [mataki/rubygems-leader#19]
Hi,
I noticed that data on http://rubygems-leader.herokuapp.com is not updated - i.e. on my profile there are data that are couple months old, but user page is showing last update just yesterday. Question is if this is bug in code or just updater is not running?

**Comment by mataki** [comment]
I fixed some bug!

**Comment by imanel** [comment]
Awesome - now it's working correctly!
